format = """
$directory\
$git_branch\
$git_status\
$jobs\
$fill\
$lua\
$nodejs\
$bun\
$golang\
$rust\
$docker_context\
$line_break\
$python\
$character\
"""

palette = 'colors'

[palettes.colors]
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[fill]
symbol = ' '

[git_branch]
style = 'fg:color1'
symbol = 'ï˜ '
format = '[on](color8) [$symbol$branch ]($style)'

[git_status]
style = 'fg:color1'
format = '([\[$all_status$ahead_behind\]]($style) )'
deleted = 'ï€'
untracked = 'ï„¨'
modified = 'ï„ª'

[docker_context]
symbol = 'ğŸ‹'
style = 'fg:color1'
format = '[$symbol] ($style) $context'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[golang]
symbol = 'ğŸ¦«'
style = 'bold fg:color8'
format = '[$symbol ($version)]($style)'

[lua]
symbol = 'ğŸŒ™'
style = 'bold fg:color8'
format = '[$symbol ($version)]($style)'

[nodejs]
symbol = 'ğŸ¥¬'
style = 'bold fg:color8'
format = '[$symbol ($version)]($style)'

[bun]
symbol = 'ğŸ¥'
style = 'bold fg:color8'
format = '[$symbol ($version)]($style)'

[rust]
symbol = 'ğŸ¦€'
style = 'bold fg:color8'
format = '[$symbol ($version)]($style)'

[python]
symbol = 'ğŸ'
style = 'bold fg:color8'
format = '[$symbol ($version) ($virtualenv)]($style)'
